import { ItemProduct } from '../../models/itemProduct'

const fake_items: ItemProduct[] = [
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  },
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  },
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  },
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  },
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  },
  {
    nameProduct: 'name product',
    category1: 'category1',
    category2: 'category2',
    category3: 'category3',
    category4: 'category4',
    description: 'a description of this product',
    idMethodShipping1: '111',
    idMethodShipping2: '222',
    idMethodShipping3: '333',
    idProduct: '1',
    idProductSeller: '1',
    idSeller: '1',
    imageURL: 'a url for the image',
    img1: 'a url',
    img2: 'a url',
    img3: 'a url',
    img4: 'a url',
    normalPrice: 100.0,
    pricePromotional: 99.9,
    stateProduct: 'offert'
  }
];

export default fake_items;
